### ISSUE TITLE
Python packages

### ISSUE THREAD

**Issue by matejdivecky** [agajdosi/unhuman-resources#22]
Package **aiohttp** is missing from the dependency list. 

Also,
`pip3 install tornado, requests, beautifulsoup4, tldextract, pysocks, lxml` 
is not using valid pip install syntax, i propose:
`pip3 install tornado requests beautifulsoup4 tldextract pysocks lxml aiohttp`
or using requirements.txt to remove depencency on readme.md

**Comment by agajdosi** [comment]
Hi @matejdivecky, thank you for the catch. I have added `requirements.txt` in https://github.com/agajdosi/unhuman-resources/commit/31b83d565b4761e30dd8c48afffffa5fe11d30eb as you suggested - using `pipreqs` + I have manually added `lxml` which is needed by BeautifulSoup. Also I have fixed the readme to mention `pip3 install -r requirements.txt` instead of wrong list of packages.

I really need to get some better understanding about package management in Python - I only have knowledge about how do it properly in Golang, but I am such a chaotic person in Python and modules...
